### ISSUE TITLE
Percentage display

### ISSUE THREAD

**Issue by darkang3lz92** [jamesblasco/arb_editor#4]
The percentage only work when provided locale resource id is not exist.  If the provided files resource id is exist but empty text, it will still show as 100%. 

Anything lesser than 100% should use other color to make a distinction.

**Comment by darkang3lz92** [comment]
Added PR #2, if that helps.

**Comment by jamesblasco** [comment]
Fixed on [#2]( https://github.com/jamesblasco/arb_editor/pull/2)
