### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [jamesblasco/arb_editor#6]
The download button doesn't seem to work. Is this known/wanted? This is a problem for me as I translated 1000+ Strings and do not want do do this again.
Using Firefox 73 on Linux 5.5.

**Comment by jamesblasco** [comment]
There is a bug sometimes when creating a new resource. I am working on it. 

Try to refresh the website (the data should save) and  check if any resource has an empty id and says undefined. 

I am sorry that you had this problem, the project is very experimental. Let me know if that temporarily solves it

**Comment by TheOneWithTheBraid** [comment]
How do you mean *empty ID*?

I don't have any empty label or fully empty resources but I do have resources only translated into some of the languages.

**Comment by TheOneWithTheBraid** [comment]
It's displaying my project in the home page with an empty label/no name.

**Comment by jamesblasco** [comment]
Could you add a label there, and try if it works?

**Comment by TheOneWithTheBraid** [comment]
How do I do?
![screenshot](https://user-images.githubusercontent.com/29313398/75612186-8a444600-5b21-11ea-9e23-30c5969e4012.png)

**Comment by jamesblasco** [comment]
Wow that looks weird haha
Click the white thin card below recent projects

**Comment by TheOneWithTheBraid** [comment]
O know, I did but how can I name it?
![image](https://user-images.githubusercontent.com/29313398/75612393-36d2f780-5b23-11ea-9298-dc77246d5894.png)

**Comment by jamesblasco** [comment]
Did you start with an arb file called intl? That should be fine.

Check in that page if there is a resource with 'undefined' label id

**Comment by TheOneWithTheBraid** [comment]
No, there isn't. Yes, my first resource was called intl_en.arb . Still, it doesn't export/download...

**Comment by TheOneWithTheBraid** [comment]
I get the following JS error when pressing the download button:
```
Another exception was thrown: Instance of 'minified:bz<void>'
```
in ` js_primitives.dart:49`

The **file** contains (according to the network debugger)
```
Error while fetching an original source: NetworkError when attempting to fetch resource.
Source URL: org-dartlang-sdk:///sdk/lib/_internal/js_runtime/lib/js_primitives.dart
```

**Comment by jamesblasco** [comment]
and any of them has same name or no alphanumeric chars no?

**Comment by jamesblasco** [comment]
It is failing to parse the dart object to arb file

**Comment by TheOneWithTheBraid** [comment]
No duplicate names and except of `shortTest5Exercises` no numbers, spaces or special characters in the labels.

**Comment by jamesblasco** [comment]
I am going to work on improving the error while parsing, so I can detect better where the error comes. If you need the translation right away, I would suggest you to use this tool https://localise.biz/, otherwise I could try to fix it on Monday

**Comment by TheOneWithTheBraid** [comment]
I can have a little hack to. I only hope my browser won't clean it's cache. I did some hours of work to manually translate about 1200 Strings into German, French and Klingon.

**Comment by TheOneWithTheBraid** [comment]
Anyway, thank you for the quick help!

**Comment by jamesblasco** [comment]
I will do my best to solve it

**Comment by jamesblasco** [comment]
Could you refresh and check the error again? It should have a better description

**Comment by TheOneWithTheBraid** [comment]
```
Error in <unknown source>: Unterminated string literal.

Error in <unknown source>: Unterminated string literal.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.
```

**Comment by jamesblasco** [comment]
Nothing that starts with `Error: `? Those errors appear when tap on the download button?

**Comment by TheOneWithTheBraid** [comment]
Just:
```
Error in parsing intl_strings.dart, no messages extracted. js_primitives.dart:49
Error in <unknown source>: Unterminated string literal.

Error in <unknown source>: Unterminated string literal.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.

Error in <unknown source>: Expected to find ','.
js_primitives.dart:49
```
Yes, they appear when pressing the download button.

**Comment by jamesblasco** [comment]
What about now? I uploaded a new version

**Comment by TheOneWithTheBraid** [comment]
Thank you so much! It's working!
May you tell me what the issue was?

**Comment by jamesblasco** [comment]
Some generated translation file arb was not being parsed correctly when creating the intl_string.dart.
Maybe you lost a translation in flutter, could you check the console if it tells you which file is the one throwing the error.
It would be very valuable for me if you could share with me the translation files so I can take a deeper look in what the real problem is. You can share it to hi@jaimeblasco.com if you want 🙂

**Comment by TheOneWithTheBraid** [comment]
The file I initially uploaded are available on GitLab under the terms and conditions of the EUPL-1.2: https://gitlab.com/testapp-system/testapp-flutter/-/blob/632ff7153ea69729b77701899a49d96e36ac5168/lib/l10n/intl_en.arb
Note: the camel-case Issue was already resolved after uploading/before trying to download.
